### ISSUE TITLE
Canonical / duplicate content

### ISSUE THREAD

**Issue by DarrenHuangTW** [hsuanchi/Max-Newsletter#1]
* **"/" and "/zh/" have same content.**
Should keep just one version and redirect the other

* **"/", "/zh/", and "/en/" all canonical to "/"**
Should be self referencing, "/zh/" canonicalize to /zh/, and /en/ canonicalize to /en/.

**Comment by hsuanchi** [comment]
@DarrenHuangTW You're right! Thanks!
