### ISSUE TITLE
NameError: name 'app' is not defined

### ISSUE THREAD

**Issue by tai271828** [hsuanchi/Max-Newsletter#10]
The recent poetry migration seems to cause regression. By building the latest code base (commit: 16df6dd27c21c1a9860500160d5969566f481b62 ) via docker-compose[1], the log shows errors when loading the landing page. See [2]. Besides, I did not provide any `.flaskenv` in this case.

Expected result: the landing page is loaded and shows up.
Actual result: "Internal Server Error" shown on the browser

[1] `docker-compose stop ; docker-compose rm -f ; docker-compose pull ; docker-compose -f docker-compose-dev.yml up --build -d`

[2] ` docker logs --follow flask` and open `localhost` from your browser

```
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    @app.shell_context_processor
NameError: name 'app' is not defined
```

```
Error: 
Unable to load celery application.
The module celery_worker.celery was not found.

Error: 
Unable to load celery application.
The module celery_worker.celery was not found.

Error: 
Unable to load celery application.
The module celery_worker.celery was not found.

subprocess 10 exited with code 1
subprocess 11 exited with code 1
subprocess 12 exited with code 1
--- no python application found, check your startup logs for errors ---
[pid: 14|app: -1|req: -1/1] 172.18.0.1 () {52 vars in 1172 bytes} [Thu Dec 10 19:04:47 2020] GET /zh/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 14|app: -1|req: -1/2] 172.18.0.1 () {52 vars in 1104 bytes} [Thu Dec 10 19:04:47 2020] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
```

**Comment by tai271828** [comment]
`git bisect` shows the latest good commit is `8840cfd27e113177882b962b217223d7cfd7c98d`.

**Comment by tai271828** [comment]
OK I was aware that I did not use .flaskenv in the testing docker env. Let me add this info in the bug description.

**Comment by hsuanchi** [comment]
After I testing #11 & #12, it seems to be working fine now, am I missing anything? if not I will close this issue :p
