### ISSUE TITLE
If there is no subscriber, the counting number is incorrect

### ISSUE THREAD

**Issue by tai271828** [hsuanchi/Max-Newsletter#6]
# Bug Description
If there is no subscriber, the counting number is incorrect

# Steps to Reproduce
Please use this ephemeral env to launch an empty db https://github.com/hsuanchi/Max-Newsletter/pull/5

# Expected Result
The page will show 0 subscriber

# Actual Result
The page shows 100 subscribers. Reproducing rate: 100%

**Comment by hsuanchi** [comment]
Thanks a lot! Orz
